
import {
	ShoppingCartIcon,
	UtensilsIcon,
	HouseIcon,
	DumbbellIcon,
	HeartPulseIcon,
	BookOpenIcon,
	BriefcaseBusinessIcon,
	GiftIcon,
	WalletIcon,
	PiggyBankIcon,
	CarFrontIcon,
	ReceiptTextIcon,
	TagIcon,
	ToolCaseIcon,
	TicketIcon,
	PawPrintIcon,
	PlusIcon,
	TrashIcon,
	SquarePenIcon,
	ArrowUpDownIcon,
	ArrowDownIcon,
	ArrowUpIcon,
	ArrowRightIcon,
} from "lucide-react";

export const Icons = {
	shoppingCart: ShoppingCartIcon,
	utensils: UtensilsIcon,
	house: HouseIcon,
	dumbbell: DumbbellIcon,
	heartPulse: HeartPulseIcon,
	bookOpen: BookOpenIcon,
	briefcaseBusiness: BriefcaseBusinessIcon,
	gift: GiftIcon,
	wallet: WalletIcon,
	piggyBank: PiggyBankIcon,
	carFront: CarFrontIcon,
	receiptText: ReceiptTextIcon,
	tag: TagIcon,
	toolCase: ToolCaseIcon,
	ticket: TicketIcon,
	pawPrint: PawPrintIcon,
	plus: PlusIcon,
	trash: TrashIcon,
	squarePen: SquarePenIcon,
	arrowUpDown: ArrowUpDownIcon,
	arrowDown: ArrowDownIcon,
	arrowUp: ArrowUpIcon,
	arrowRight: ArrowRightIcon,
};

export type IconType = keyof typeof Icons;